### ISSUE TITLE
Unable to Run Galaxy Installation

### ISSUE THREAD

**Issue by mneumarkidg** [SeleniumHQ/ansible-selenium#10]
ansible-galaxy install SeleniumHQ.selenium -vvvv
`
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Using /home/ansible/.ansible.cfg as config file
Opened /home/ansible/.ansible_galaxy
Installing role SeleniumHQ.selenium
Opened /home/ansible/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'selenium', owned by SeleniumHQ
https://galaxy.ansible.com/api/v1/roles/?owner__username=SeleniumHQ&name=selenium
ERROR! Unexpected Exception: name must be a byte string
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.6/site-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/usr/lib/python2.6/site-packages/ansible/cli/__init__.py", line 103, in execute
    fn()
  File "/usr/lib/python2.6/site-packages/ansible/cli/galaxy.py", line 385, in execute_install
    installed = role.install()
  File "/usr/lib/python2.6/site-packages/ansible/galaxy/role.py", line 204, in install
    role_data = api.lookup_role_by_name(self.src)
  File "/usr/lib/python2.6/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/ansible/galaxy/api.py", line 179, in lookup_role_by_name
    data = self.__call_galaxy(url)
  File "/usr/lib/python2.6/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/ansible/galaxy/api.py", line 92, in __call_galaxy
    resp = open_url(url, data=args, validate_certs=self._validate_certs, headers=headers, method=method)
  File "/usr/lib/python2.6/site-packages/ansible/module_utils/urls.py", line 846, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 389, in open
    req = meth(req)
  File "/usr/lib/python2.6/site-packages/ansible/module_utils/urls.py", line 672, in http_request
    ssl_s = ssl_wrap_socket(s, ca_certs=tmp_ca_cert_path, cert_reqs=ssl.CERT_REQUIRED, ssl_version=PROTOCOL, server_hostname=self.hostname)
  File "/usr/lib/python2.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
  File "/usr/lib/python2.6/site-packages/OpenSSL/SSL.py", line 1234, in set_tlsext_host_name
    raise TypeError("name must be a byte string")
TypeError: name must be a byte string
`

**Comment by mneumarkidg** [comment]
raise TypeError("name must be a byte string")
TypeError: name must be a byte string

**Comment by ddavison** [comment]
i'm assuming this isn't a problem anymore. closing
